//class ExceptionEx03 {
//	public static void main(String args[]) {
//		int number = 100;
//		int result = 0;
//
//		for(int i=0; i < 10; i++) {
//			try {                                  // 0-9까지 , 만약 0이걸리면 에러 
//				result = number / (int)(Math.random() * 10);
//				System.out.println(result);
//				} 
//			catch (ArithmeticException e)	{
//				System.out.println("0");	
//			} // try-catch의 끝
//		} // for의 끝
//	
//	} 
//}
